# PCA - Method 1

## Get the data

In [1]:
import pandas as pd

In [13]:
# import the standardized data into a dataframe
data = pd.read_csv("../data/standardized_data.csv")

In [4]:
# view top 5 rows of the data
data.head()

,GEOID,tract,not_citizen,naturalized_citizen,native_citizen,foreign_born,work_from_home,desktop_or_laptop,desktop_or_laptop_only,smartphone,...,access_with_no_subscription,no_internet_access,sixty_five_and_older,median_income,mean_income,mean_d_mbps,mean_u_mbps,mean_lat_ms,number_providers,mean_lowest_cost
0,53001950100,9501.00,-0.482364,-0.136075,-0.777232,-0.423714,-0.510108,-0.880685,0.078368,-0.734196,...,0.186658,-0.130705,-0.398441,-0.373237,-0.506775,-1.621869,-0.934956,0.733392,1.709422,-1.274819
1,53001950200,9502.00,0.087773,-1.067185,-1.423574,-0.347869,-0.865321,-1.483304,-1.169515,-1.434819,...,-0.617730,-0.336734,-1.275177,-0.049144,-0.608391,-1.629913,-0.953501,1.633077,1.709422,-0.741817
2,53001950301,9503.01,2.028432,-0.818167,-1.843209,1.240681,-1.311874,-1.888989,-1.244016,-1.823626,...,-0.580317,0.124379,-1.177059,-0.935569,-0.917475,-1.321690,-0.794596,1.596865,-0.296448,-1.638231
3,53001950302,9503.02,2.494409,0.946610,-1.389043,2.285668,-1.078448,-1.764920,-1.560643,-1.336655,...,-0.449370,-0.611440,-1.180224,-0.093647,-0.261890,-1.334392,-0.651406,0.821234,-0.296448,-1.638231
4,53001950303,9503.03,2.351875,0.232038,-1.259924,1.898011,-0.225938,-1.585710,-1.448892,-1.284685,...,-0.617730,-0.827280,-1.139077,-0.447587,-0.091572,-1.486311,-0.757763,0.499425,-0.296448,-1.638231

In [14]:
# remove the columns that I don't want (geoid, tract)
data = data.drop(columns=["GEOID", "tract"])
data.head()

,not_citizen,naturalized_citizen,native_citizen,foreign_born,work_from_home,desktop_or_laptop,desktop_or_laptop_only,smartphone,smartphone_only,tablet_or_portable,...,access_with_no_subscription,no_internet_access,sixty_five_and_older,median_income,mean_income,mean_d_mbps,mean_u_mbps,mean_lat_ms,number_providers,mean_lowest_cost
0,-0.482364,-0.136075,-0.777232,-0.423714,-0.510108,-0.880685,0.078368,-0.734196,0.547053,-0.764807,...,0.186658,-0.130705,-0.398441,-0.373237,-0.506775,-1.621869,-0.934956,0.733392,1.709422,-1.274819
1,0.087773,-1.067185,-1.423574,-0.347869,-0.865321,-1.483304,-1.169515,-1.434819,-0.463206,-1.436186,...,-0.617730,-0.336734,-1.275177,-0.049144,-0.608391,-1.629913,-0.953501,1.633077,1.709422,-0.741817
2,2.028432,-0.818167,-1.843209,1.240681,-1.311874,-1.888989,-1.244016,-1.823626,-0.368123,-1.768240,...,-0.580317,0.124379,-1.177059,-0.935569,-0.917475,-1.321690,-0.794596,1.596865,-0.296448,-1.638231
3,2.494409,0.946610,-1.389043,2.285668,-1.078448,-1.764920,-1.560643,-1.336655,0.297460,-1.314998,...,-0.449370,-0.611440,-1.180224,-0.093647,-0.261890,-1.334392,-0.651406,0.821234,-0.296448,-1.638231
4,2.351875,0.232038,-1.259924,1.898011,-0.225938,-1.585710,-1.448892,-1.284685,-0.118529,-1.489509,...,-0.617730,-0.827280,-1.139077,-0.447587,-0.091572,-1.486311,-0.757763,0.499425,-0.296448,-1.638231